[package]
name = "dump-pic"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
image = "^ 0.23"
structopt = "^ 0.2"
ansi = { path = "../../libs/nitrogen/system/ansi" }
lib = { path = "../../libs/lib" }
pal = { path = "../../libs/pal" }
pic = { path = "../../libs/pic" }