variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - whoami
  - groups
  - nix shell github:oxalica/rust-overlay -c rustc --version
  - nix shell github:oxalica/rust-overlay -c nix-shell --run "cargo install cargo-nextest --locked"

check_format:
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - nix shell github:oxalica/rust-overlay -c cargo fmt --all -- --check

check_clippy:
  interruptible: true
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - nix shell github:oxalica/rust-overlay -c nix-shell --run "cargo clippy --workspace --all-targets -- --deny warnings"

check_test:
  interruptible: true
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - nix shell github:oxalica/rust-overlay -c nix-shell --run "cargo nextest run --workspace --all-targets --no-fail-fast"
  retry: 2 # Sometimes X clients just crash

