[package]
name = "dump-lib"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^ 1"
humansize = ">= 1.0.1"
structopt = "^ 0.2"
catalog = { path = "../../libs/nitrogen/system/catalog" }
lib = { path = "../../libs/lib" }