[package]
name = "dump-xt"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^ 1"
simplelog = "^ 0.5"
structopt = "^ 0.2"
lib = { path = "../../libs/asset/lib" }
xt = { path = "../../libs/asset/xt" }
