[package]
name = "dump-xt"
version = "0.0.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = { version = "^ 1", features = ["backtrace"] }
simplelog = "^ 0.5"
structopt = "^ 0.2"
lib = { path = "../../libs/asset/lib" }
xt = { path = "../../libs/asset/xt" }
