[package]
name = "dump-xt"
version = "0.0.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = { version = "^ 1", features = ["backtrace"] }
env_logger = "^ 0.9"
structopt = "^ 0.3"
absolute_unit = { path = "../../libs/nitrogen/util/absolute_unit" }
catalog = { path = "../../libs/nitrogen/system/catalog" }
lib = { path = "../../libs/asset/lib" }
xt = { path = "../../libs/asset/xt" }
pt = { path = "../../libs/asset/pt" }
