[package]
name = "dump-sh"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^ 1"
structopt = "^ 0.2"
simplelog = "^ 0.5"
i386 = { path = "../../libs/util/i386" }
lib = { path = "../../libs/asset/lib" }
reverse = { path = "../../libs/util/reverse" }
sh = { path = "../../libs/asset/sh" }
