[package]
name = "dump-asm"
version = "0.0.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^ 1"
simplelog = "^ 0.5"
structopt = "^ 0.2"
i386 = { path = "../../libs/util/i386" }