[package]
name = "dump-lay"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^ 1"
structopt = "^ 0.3"
lib = { path = "../../libs/asset/lib" }
lay = { path = "../../libs/asset/lay" }
pal = { path = "../../libs/asset/pal" }
