[package]
name = "dump-pe"
version = "0.0.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = { version = "^ 1", features = ["backtrace"] }
structopt = "^ 0.2"
ansi = { path = "../../libs/nitrogen/util/ansi" }
lib = { path = "../../libs/asset/lib" }
peff = { path = "../../libs/util/peff" }