[package]
name = "dump-pe"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
structopt = "^ 0.2"
ansi = { path = "../../libs/nitrogen/system/ansi" }
lib = { path = "../../libs/lib" }
peff = { path = "../../libs/peff" }